### ISSUE TITLE
[Enhancement] Improve Library Loading Time

### ISSUE THREAD

**Issue by NVHT** [syntax-tm/SteamAchievementManager#12]
It takes too long for SAM to load the entire library if you had lots of games. In my case, I have more than 3k games in my Steam library.

**Comment by SandeMC** [comment]
just stop having 3k games in your library ez fix

**Comment by syntax-tm** [comment]
Does the old version of SAM take a long time to load your library? Because they both check the same list of apps the same way.

**Comment by NVHT** [comment]
> Does the old version of SAM take a long time to load your library? Because they both check the same list of apps the same way.

It is much faster. It takes about 30 seconds plus a bit more icons download time to display the entire library.

Your version at least 20-30 minutes to load everything.

**Comment by psy0ch** [comment]
Can confirm that old SAM is vastly faster then the current implementation of this release.

A search by name/appid would also be great, to ignore the image gridwall and immediately finding the correct game

**Comment by syntax-tm** [comment]
Thanks for confirming it. Sadly I have <3k games so I can't really test it myself so I appreciate the help.

I've got some ideas though. If I have extra time this week I'll see what I can do.

**Comment by syntax-tm** [comment]
I made some changes to the startup. When you get a chance you can test the changes in the [v0.3.0-alpha](https://github.com/syntax-tm/SteamAchievementManager/releases/tag/v0.3.0-alpha) release. Let me know if things are better or worse or if you run into any other issues.

@psy0ch As far as the search functionality goes, the hardest part would be the UI/UX. Where to add the search bar, should it have placeholder text, auto hide/expand, focus/hover styles, clear button, does it search by name only, should search results be sorted, if so what order, etc. If you have suggestions feel free to create a new issue so it can be tracked. It's something I have planned on doing but haven't gotten around to it yet.

**Comment by syntax-tm** [comment]
@psy0ch Great to hear. I went ahead and added the search functionality too and that should work for the app names and ids. I'm going to close this but feel free to re-open it or create a new issue if anything else comes up. ✌️
