### ISSUE TITLE
issue with baldur's gate 3

### ISSUE THREAD

**Issue by jackwaecow** [syntax-tm/SteamAchievementManager#16]
![image](https://github.com/syntax-tm/SteamAchievementManager/assets/107541724/b8a10e39-5a28-45b5-89aa-e3e330e55db3)

**Comment by syntax-tm** [comment]
Can you share the log for that exception? There should be one in the `/logs/errors.txt`. My guess is that it's maybe protected but non-achievement user stats are rare and protected user stats are even more rare (I can't think of any off the top of my head).

I don't own Baldur's Gate 3 so I can't check it myself but I verified that stat save is working for me.

**Comment by syntax-tm** [comment]
Did some more testing and was able to get (hopefully) that error when saving a stat. In my case, I was setting trying to save `99` to `98` and got the `Failed to update Integer stat XXXXXX` error.

I checked and saw that the stat definition had `incrementOnly` set to `true` but that wasn't reflected in the UI (the grid in `SAM.Manager`). This has been fixed and the changes can be viewed here:

dfed13100a7e23a67a8cec846b596a294a5fe235

If you want to test this you can download the build artifact [here](https://github.com/syntax-tm/SteamAchievementManager/actions/runs/8339223685) (click the **SAM** link in the **Artifacts** section).

Note that this will only fix the "__Increment Only__" column not displaying properly.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/e7746986-b9ef-4da7-8bce-cd5a70bc5f11)

Ideally validation should be done upon editing and if any errors are present they should be highlighted and prevent you from saving. So, I created an issue to track adding (actual) validation for `incrementOnly`.

#17

**Comment by jackwaecow** [comment]
![image](https://github.com/syntax-tm/SteamAchievementManager/assets/107541724/3b5b8bfd-8ab3-46e6-b120-e3777d03a75f)
2024-03-19 01:58:43,580 [1] FATAL App [(null)] - No app ID argument was supplied. Application will now exit...
2024-03-19 01:59:10,849 [1] ERROR SteamGameViewModel [(null)] - An error occurred attempting to save stats. Failed to update Integer stat BG3_Quest09_STAT.
SAM.Core.SAMException: Failed to update Integer stat BG3_Quest09_STAT.
   at SAM.Core.ViewModels.SteamGameViewModel.SaveStats() in /_/src/SAM.Core/ViewModels/SteamGameViewModel.cs:line 153
2024-03-19 01:59:19,658 [1] ERROR SteamGameViewModel [(null)] - An error occurred attempting to save stats. Failed to update Integer stat BG3_Quest09_STAT.
SAM.Core.SAMException: Failed to update Integer stat BG3_Quest09_STAT.
   at SAM.Core.ViewModels.SteamGameViewModel.SaveStats() in /_/src/SAM.Core/ViewModels/SteamGameViewModel.cs:line 153

**Comment by jackwaecow** [comment]
you are right, it can only increase but not decrease

**Comment by syntax-tm** [comment]
Yeah, I never noticed it so I must have always incremented when testing that and didn't know it wasn't showing properly. When I tested it earlier I just incremented the first stat value in L4D and then I went to test it again and tried to undo that earlier save and that's when I got the error and noticed that wasn't set properly in the UI.

I'll eventually add nice validation and stuff so to make this more obvious sometime in the future.

---

In the meantime, if you really want to reset the stat, I'm 90-ish percent sure that you can use the Steam console's `reset_all_stats` function.

If you've never used the Steam console, the easiest way is to open the Windows Run dialog (`Win + R`) and then type `steam://open/console`.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/8581e045-d786-46bb-b542-b0e83d665c83)

Click "OK" and Steam should open the Console tab.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/705437e3-6428-457f-b5b9-c7029d070820)

Here you can type `reset_all_stats <appid>` and press Enter and you should see `reset_all_stats success for appid <appid>`. In your case, Baldur's Gate 3's appid is `1086940` so you would enter:

```sh
reset_all_stats 1086940
```

> [!NOTE]  
> You will need to have the app installed in order to be able to reset the stats.

**Comment by jackwaecow** [comment]
![image](https://github.com/syntax-tm/SteamAchievementManager/assets/107541724/336519f9-86ff-4b65-a543-fd2a76ea5de4)
which app do I need to install?

**Comment by jackwaecow** [comment]
steam console method actually doesn't work either 
![image](https://github.com/syntax-tm/SteamAchievementManager/assets/107541724/b2bf500f-ca36-4a0b-b253-47368cefe5ce)

**Comment by syntax-tm** [comment]
Is SAM running? Try closing out of it first.

**Comment by jackwaecow** [comment]
it didn't help, still doesn't work

**Comment by syntax-tm** [comment]
@jackwaecow i'll buy the game and see what i can do. i think it's just the order of operations that's the issue. basically, if the stats or your save used to generate those stats are still available then the reset won't be permanent.

I just tested this with Left 4 Dead to make sure it works but here's the full order of operations:

1. Launch Steam
2. Install game
3. Turn off auto updates
4. Turn off Steam cloud sync
5. Open Steam console
   - Press `Win + R`
   - Type `steam://open/console`
   - Click **OK**
7. Run `reset_all_stats <id>`
   - Where `<id>` is the app's id
8. Play game
   - Get to a point where you can save the game
9. Exit game
10. Enable Steam cloud

If you load any of your previous save data then you're likely going to immediately unlock all of your previous achievements along with your stats being restored as well. The key to making it persist is just having your local data, which you have reset, be newer than what's in the cloud so when you re-enable Steam cloud it overwrites the cloud data with your (reset) local data.

**Comment by teolabx** [comment]
I found an option to disable the automatic opening of achievements from the rockstar account. But achievements will no longer open automatically on steam, you will have to open each manually via SAM. But it's better than opening all at once at the same time through syncing with rockstar. Using the example of RDR2 . In the directory "C:\Users\USERNAME\OneDrive\Documents\Rockstar Games\Social Club\Profiles\********\ Titles\Red Dead Redemption 2" open the file "achievements.dat" using notepad. You need to delete everything. Click save. It is mandatory to set the "read-only" attributes to the file. That's it
