### ISSUE TITLE
SAM crashes after loading large library

### ISSUE THREAD

**Issue by Mandydeth** [syntax-tm/SteamAchievementManager#26]
When launching a library of over 5000 games, SAM crashes without error after loading 100% of the library. I'm able to interact with SAM as it's loading and click a game before the crash, but the main window crashes without error the majority of the time.

After attempting to open it several times I've finally been able to generate an error:

`SAM (1465860) 2024-07-28 10:50:47,506 ERROR SteamStatsManager [8] - An error occurred handling stats retrieval. Specified argument was out of the range of valid values. (Parameter 'stat')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'stat')
   at SAM.Stats.SteamStatisticFactory.CreateStat(Client client, StatInfoBase stat) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\Factories\SteamStatisticFactory.cs:line 57
   at SAM.Stats.SteamStatsManager.GetStatistics() in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 279
   at SAM.Stats.SteamStatsManager.OnUserStatsReceived(UserStatsResponse param) in D:\a\SteamAchievementManager\SteamAchievementManager\src\SAM\Stats\SteamStatsManager.cs:line 144`

I've noticed the original branch of SAM functions normally as well as SAM Auto, so I'm unsure if it's a matter of how large libraries being considered outside of the range of valid values.

**Comment by Mandydeth** [comment]
Upon further review, I believe it's do to the inability to translate certain Unicode characters some examples: 
🔴 Circles
🕌魔塔与6️⃣勇者  (Six Braves)

I've tested a change on my own fork and it seems to have resolved the issue.

**Comment by SandeMC** [comment]
why close the issue? it's not solved here as far as i can tell

**Comment by syntax-tm** [comment]
> Upon further review, I believe it's do to the inability to translate certain Unicode characters some examples: 🔴 Circles 🕌魔塔与6️⃣勇者 (Six Braves)
> 
> I've tested a change on my own fork and it seems to have resolved the issue.

Heyo, I just now saw this because you closed it too fast, I can make the change here for the unicode fix or if you wanted to make a PR that would be cool too.
