### ISSUE TITLE
[Question/Help] Build/Compile from Source Code

### ISSUE THREAD

**Issue by SantiagoFeresin** [syntax-tm/SteamAchievementManager#5]
Since there's no releases page or build instructions, I tried searching how to compile it myself. I had a lot of errors and couldn't compile.
I was hoping if you could give some insight on how to do it, or alternatively upload the app already compiled.

**Comment by syntax-tm** [comment]
I'd have to look and see what you're using to try and compile it. I'm using VS2022 Enterprise (though any other edition should work fine). The projects are all .NET 7 so you'll need that installed. You can run `dotnet --info` to see what versions of the .NET SDKs, runtimes, etc. are installed. Here's the output when I run `dotnet --info` on my local machine:

```txt
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

From within Visual Studio, you can use `Debug` or `Release` configurations, but the platform needs to be `x86` because Steam, and more specifically `steamclient.dll`, are 32-bit.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/07372dc6-641c-426d-afc1-d6a7cad63fd8)

You can add me on Discord (`@gundwn`) or something if you have more questions on it. I don't have binaries uploaded here since it's still very much a work in progress. Worst case scenario I can build it and send them on Discord in a zip or something if you want.

**Comment by syntax-tm** [comment]
When you get a chance try pulling down the latest and rebuilding.

**Comment by BasedOnPixels** [comment]
Hello, hope it's fine for me to comment here. I've been able to compile it fine even before the update 2 days ago, after installing .Net 7. I tried with the latest update and without, but I have been unable to run the exe successfully. It always starts up with an error along the lines of:

"An error occured on application startup. Line "14" and line position "14". Provide value on 'DevExpress.Mvvm.UI.ViewModelSourceExtension' threw an exception.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13744383/acd1093c-7229-4486-a70e-8b3eb09a6019)

**Comment by syntax-tm** [comment]
@BasedOnPixels Totally fine, and thanks for translating. I wonder if it's something with the DevExpress MVVM library's localization. I can try updating it to the latest along with the rest of the dependencies.

In the meantime, there should be a log file created in `\logs\errors.txt` as well as a normal log file in `\logs\log.txt`. Can you check and see if there's more information (like the stacktrace or innerexception) that was logged?
