### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by tonwhite** [syntax-tm/SteamAchievementManager#9]
Salute! 
Could you please add a ready-to-use release version of the app or a short text-guide on how to compile an app yourself

P.S. Huge thanks for your work on the SAM project

**Comment by syntax-tm** [comment]
I'm in the middle of making an actual first release for the project. Currently testing the stats functionality so be aware that's still in-progress (specifically the average rate stats).

In the meantime though, I setup GitHub Actions for the project somewhat recently so there's automatic builds for every commit.

You can view the recent runs for the workflow(s) here:
https://github.com/syntax-tm/SteamAchievementManager/actions

Using [the most recent one](https://github.com/syntax-tm/SteamAchievementManager/actions/runs/6281547880) as an example (at the time of writing this comment), you can see the build artifact `SAM` listed at the bottom under the _Artifacts_ section.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/5859e665-5a1c-4fb6-9c82-e1c3cc6f4269)

If you click that, it will download the build artifact as a `.zip` which you can then extract to wherever. Once you have extracted the files, run the `SAM.exe` to start the app.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/d77b928e-1393-4531-a4f5-a055ad196adb)

Assuming everything worked properly, you should see your Steam library.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/40dcf2da-ae34-46c0-b0fe-1b57a5b3598f)

To manage a game you can either double click the tile or you can right-click one to open the context menu and select "_Open in Manager_".

**Comment by syntax-tm** [comment]
I created the first release so I'm going to close this. If you need anything else feel free to reach out or open another issue. Thanks!
